export const Fild_config = {
    Title: "text",
    Year: "text",
    Released: "text",
    Runtime: "text",
    Director: "text",
    Actors: "text",
    Plot: "text",
    Country: "text",
    imdbRating: "text",
    imdbVotes: "text",
    Rated:"text",
    Awards:"text",
    Language:"text",
    Writer:"text"
  }
  
  export const template = {
   url_name: "",
   Title: "",
   Year: "",
   Released: "",
   Runtime: "",
   Genre: [],
   Director: "",
   Actors: "",
   Plot: "",
   Country: "",
   imdbRating: "",
   imdbVotes: "",
   Type: "",
   Images: [],
   Downloads: [],
   New: false,
   Trand: false,
   Poster: "",
   AutoShow: true,
   UploadedImageIds: [],
   Featured: false,
   Category: "",
   Language: "",
   Rated: "",
   Writer: "",
   Awards:"",
   Banner:""
}